name: E2E Tests

# TODO: temporarily disabled until EAS workflow issues are fixed
#on:
#  pull_request: {}
#  push:
#    branches:
#      - main

jobs:
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: development

  build_android:
    name: Build Android App
    type: build
    params:
      platform: android
      profile: development

  e2e-ios:
    name: Run E2E Tests (iOS)
    needs: [build_ios]
    type: maestro
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path: ["./e2e/*.yaml"]

  e2e-android:
    name: Run E2E Tests (Android)
    needs: [build_android]
    type: maestro
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path: ["./e2e/*.yaml"]
