name: CI Checks

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          # Increase max argument size limit
          sysctl -w kernel.pid_max=100000
          # Install dependencies with increased memory
          NODE_OPTIONS="--max-old-space-size=4096" pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            coverage/
            test-results/
          retention-days: 7

      - name: Build
        run: pnpm build
