name: Web CI Checks

on:
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/**"
      - "configs/**"
  push:
    branches: ["main"]
    paths:
      - "apps/web/**"
      - "packages/**"
      - "configs/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  web-ci:
    name: Web CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter web...

      - name: Lint
        run: pnpm --filter web lint

      - name: Format
        run: pnpm --filter web format

      - name: Typecheck
        run: pnpm --filter web typecheck

      - name: Test
        run: pnpm --filter web test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: web-test-results
          path: |
            apps/web/coverage/
            apps/web/test-results/
          retention-days: 7

      - name: Build
        run: pnpm -F web build
