name: Mobile CI Checks

on:
  pull_request:
    paths:
      - "apps/mobile/**"
      - "packages/**"
      - "configs/**"
  push:
    branches: ["main"]
    paths:
      - "apps/mobile/**"
      - "packages/**"
      - "configs/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}

jobs:
  mobile-ci:
    name: Mobile CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter mobile...

      - name: Lint
        run: pnpm --filter mobile lint

      - name: Format
        run: pnpm --filter mobile format

      - name: Typecheck
        run: pnpm --filter mobile typecheck

      - name: Test
        run: pnpm --filter mobile test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mobile-test-results
          path: |
            apps/mobile/coverage/
            apps/mobile/test-results/
          retention-days: 7

      - name: Build
        run: pnpm -F mobile build
